apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-service
  namespace: platform
spec:
  scaleTargetRef:
    name: order-service
  minReplicaCount: 2
  maxReplicaCount: 8
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
        metricName: app_requests_rate
        query: sum(rate(app_requests_total[2m]))
        threshold: "5"
