apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../kubernetes/namespace.yaml
  - ../../../kubernetes/configmap.yaml
  - ../../../kubernetes/services/order-service.yaml
  - ../../../kubernetes/services/payment-service.yaml
  - ../../../kubernetes/services/notification-service.yaml
  - ../../../kubernetes/deployments/order-service.yaml
  - ../../../kubernetes/deployments/payment-service.yaml
  - ../../../kubernetes/deployments/notification-service.yaml
  - ../../../kubernetes/hpa/order-service.yaml
